mod codegen;
mod datapack;
mod lex;
mod parse;
mod utility;

use anyhow::Result;
use codegen::codegen;
pub use datapack::Datapack;
use lex::lex;
use parse::parse;

pub fn compile(source: &str) -> Result<Datapack> {
    let functions = codegen(parse(lex(source)?)?);

    Ok(Datapack {
        description: "Datapack generated by MCML".to_owned(),
        pack_format: 18,
        functions,
    })
}
